### ISSUE TITLE
Register version 1.0

### ISSUE THREAD

**Issue by serenity4** [JuliaServices/AutoHashEquals.jl#23]
Hi, it looks like the 1.0 version [has not been registered](https://github.com/JuliaRegistries/General/blob/master/A/AutoHashEquals/Versions.toml), would you mind triggering the registrator such that the latest version can be used in other packages?

**Comment by iamed2** [comment]
I think only @andrewcooke has permissions to change repo settings and I think that's why [registration isn't working](https://github.com/andrewcooke/AutoHashEquals.jl/commit/56ed670865e0c17116cde18e30450d954fec5893#commitcomment-59652803)

**Comment by gafter** [comment]
@JuliaRegistrator register()

**Comment by gafter** [comment]
Registration wasn't working because the wrong version number was in the `Project.toml` file.

**Comment by gafter** [comment]
@JuliaRegistrator register()

**Comment by gafter** [comment]
Version 1.0 of this package has been registered.
