### ISSUE TITLE
Move repo to an org

### ISSUE THREAD

**Issue by iamed2** [JuliaServices/AutoHashEquals.jl#31]
I'm not sure what the best org is for this repo, but I believe an org would allow a better maintenance environment with multiple people who can make changes like add GitHub Apps or Secrets.

Ideally @andrewcooke is willing to transfer it once an org is decided (he hasn't engaged with this repo since early 2017 AFAICT), but if he doesn't respond I suppose we could migrate to a fork.

**Comment by gafter** [comment]
I would be interested in helping move this to https://github.com/RelationalAI-oss

**Comment by gafter** [comment]
I now have https://github.com/JuliaServices/AutoHashEqualsCached.jl.  I would be happy to (rename that repo and) make that the next revision of this package if you are interested.

**Comment by gafter** [comment]
This package is now in the `JuliaServices` org.
