### ISSUE TITLE
broken on julia 0.6

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaServices/AutoHashEquals.jl#8]
I get the following error on julia master:
```julia
julia> include("runtests.jl")
ERROR: LoadError: syntax: field name "Main.j" is not a symbol
Stacktrace:
 [1] include_from_node1(::String) at ./loading.jl:539
 [2] include(::String) at ./sysimg.jl:14
while loading /home/carlo/Git/AutoHashEquals.jl/test/runtests.jl, in expression starting on line 56
```

**Comment by andrewcooke** [comment]
this seems to be because the "dummy()" macro does not escape what it returns.  if you change it's result to `esc(x)` then this error disappears.

however, that then reveals another error i don't yet understand.

**Comment by andrewcooke** [comment]
the other error was fixed by not having docs in a nested element.  there's something weird about docs, but it seems like it's julia's problem, not mine.
